AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Autorizador - Lambda para realizar o login
Parameters:
  Environment:
    Description: Environment
    Type: String
  UsuariosTableName:
    Description: Usuarios Table Name
    Type: String
  TokenTableName:
    Description: Token table name
    Type: String

Resources:  
  AutorizadorLambdaRealizarLoginFn:
    DependsOn: AutorizadorLambdaRealizarLoginLogGroup
    Type: AWS::Serverless::Function
    Properties:
      Description: register an user on database
      FunctionName: !Join ["_", [!Ref Environment, "escoladesoftware-autorizador-lambdarealizarloginfn"]]
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs18.x
      Timeout: 2
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          UsuariosTableName: !Ref UsuariosTableName
          TokenTableName: !Ref TokenTableName
    Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: Autorizador
      - Key: Servico
        Value: Lambda

  AutorizadorLambdaRealizarLoginLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Environment, "_escoladesoftware-autorizador-lambdarealizarloginfn"]]
      RetentionInDays: 3
